name: deploy to remote server

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # SSH Deploy
      - name: Generate SSH key
        run: echo "$SSH_PRIVATE_KEY" > key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Set permission for SSH Key
        run: chmod 600 key
      
      - name: Add SSH key to the ssh-agent
        run: eval $(ssh-agent -s) && ssh-add key

      - name: Test SSH connection
        run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 catalysphere@sv14319.xserver.jp echo "SSH connection successful"

      - name: Deploy with rsync
        run: rsync -auvz -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./.next/* catalysphere@sv14319.xserver.jp:/home/catalysphere/catalysphere.com/public_html/app-demo001/ --exclude .htaccess
