name: deploy to remorte

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install NPM packages
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Export Next.js App
        run: npm run export

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        env:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: catalyshpere.xserv.jp/public_html/app-demo001.catalysphere.com
          local-dir: ./
          args: --delete